version: '3.8'

networks:
  shared:
    driver: bridge

services:
  web-front:
    image: node:20.5.1
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4200:4200
    command: bash -c "npm install -g npm@9.7.1 && npm install -g @angular/cli && ng serve --host 0.0.0.0"

    networks:
      - shared